<!-- Start Slider la -->
<?php $categories = $this->getAllCategories() ?>
<div>
    <div class="slideshow-container">
        <ul class="slideshow">
            <?php foreach($categories as $category ):?>
                <li><a href="<?php echo $category->getUrl() ?>"><img src="<?php echo $category->getImageUrl() ?>" alt="" /></a></li>
            <?php endforeach;?>
        </ul>
    </div>
    <div class="slideshow-pager">&nbsp;</div>
    <span class="slideshow-prev" style="height: 655px">&nbsp;</span><span class="slideshow-next" style="height: 655px">&nbsp;</span>
</div>
<!-- End Slider -->

<!-- START Category Products -->
<!--
Jewelry
Shoes
Electronics
-->
<?php $productCollection = $this->getProductsByCategory('Jewelry') ?>
<div>
    <h2>Jewelry</h2>
    <ul>
        <?php foreach($productCollection as $product ):?>
        <li>
            <h3><?php echo $product->getName() ?></h3>
            <img src="<?php echo (string)Mage::helper('catalog/image')->init($product, 'image')->resize(150) ?>">
            <h3><?php echo $product->getPrice() ?></h3>
        </li>
        <?php endforeach;?>
    </ul>
</div>


<?php $productCollection = $this->getProductsByCategory('Shoes') ?>
<div>
    <h2>Shoes</h2>
    <ul>
        <?php foreach($productCollection as $product ):?>
            <li>
                <h3><?php echo $product->getName() ?></h3>
                <img src="<?php echo (string)Mage::helper('catalog/image')->init($product, 'image')->resize(150) ?>">
                <h3><?php echo $product->getPrice() ?></h3>
            </li>
        <?php endforeach;?>
    </ul>
</div>
<!-- END Category Products -->


<!--START Latest Products -->
<?php $latestProductsCollection = $this->getLatestProducts() ?>
<div>
    <h2>Latest Products</h2>
    <ul>
        <?php foreach($latestProductsCollection as $product ):?>
            <li>
                <h3><?php echo $product->getName() ?></h3>
                <img src="<?php echo (string)Mage::helper('catalog/image')->init($product, 'image')->resize(150) ?>">
                <h3><?php echo $product->getPrice() ?></h3>
            </li>
        <?php endforeach;?>
    </ul>
</div>
<!--END Latest Products -->
